name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    strategy:
      max-parallel: 1
    runs-on: ${{ windows-latest }}
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.2
        with:
          serverURL: "http://localhost:8000/"
          clientID: "${{ secrets.DAI_CLIENT_ID }}"
          testConfigID: "2b43fd4b-c576-4f6e-9112-7b56131459aa" # Test configuration which need to perform execution
          clientSecret: "249daf3f-2a7a-4072-9b63-15f393a4ba4a" # Eggplant DAI service client secret
          # Alternatively, DAI client secret can be set as repo secret
          # by going to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"
